@startuml

class main
{
    << makes calls here >>
    + list of users (testing)
}

class OldClassesInfo
{
    ' GPA calculation model is (earned_credits / taken_credits)

    ' the number of grades to be divided
    - earned_credits
    ' the number of credits to divide by
    - taken_credits
}

class NewClassesInfo
{
    ' the list of classes added to the user (another class)
    - course_name
    - course_grade
    - course_credit_hours
}

class User
{
    - current_info
    - new_classes_list
    - last_embed_id
    - discord_user
}

' relates User with other classes
User *-down--- OldClassesInfo
User *-down--- NewClassesInfo
main *-down-- User

@enduml